services:
  - type: web
    name: angular-ssr-app
    env: node
    plan: free
    buildCommand: npm install && npm run build:ssr
    startCommand: node dist/user-app/server/main.js
    rootDir: . # ou le chemin si ton app est dans un sous-dossier
